"""files

Revision ID: 738cc3466296
Revises: e1a463aef094
Create Date: 2026-09-02 20:05:46.629959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '738cc3466296'
down_revision: Union[str, Sequence[str], None] = 'e1a463aef094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_objects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('ciphertext_sha256', sa.String(length=64), nullable=False),
    sa.Column('envelope_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=128), nullable=False),
    sa.Column('uploaded_by', sa.String(length=128), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['envelope_id'], ['envelopes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_objects_envelope_id'), 'file_objects', ['envelope_id'], unique=True)
    op.create_index(op.f('ix_file_objects_subject_id'), 'file_objects', ['subject_id'], unique=False)
    op.add_column('envelopes', sa.Column('blob_ref', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('envelopes', 'blob_ref')
    op.drop_index(op.f('ix_file_objects_subject_id'), table_name='file_objects')
    op.drop_index(op.f('ix_file_objects_envelope_id'), table_name='file_objects')
    op.drop_table('file_objects')
    # ### end Alembic commands ###
