"""initial schema

Revision ID: e1a463aef094
Revises: 
Create Date: 2026-08-23 23:35:58.689721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1a463aef094'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('key_id', sa.String(length=36), nullable=True),
    sa.Column('message_code', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=128), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.String(length=128), nullable=False),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_operation'), 'approvals', ['operation'], unique=False)
    op.create_index(op.f('ix_approvals_status'), 'approvals', ['status'], unique=False)
    op.create_index(op.f('ix_approvals_target_id'), 'approvals', ['target_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('key_id', sa.String(length=36), nullable=True),
    sa.Column('item_id', sa.String(length=128), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('prev_digest', sa.String(length=64), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_actor'), 'audit_log', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_log_digest'), 'audit_log', ['digest'], unique=False)
    op.create_index(op.f('ix_audit_log_key_id'), 'audit_log', ['key_id'], unique=False)
    op.create_index(op.f('ix_audit_log_operation'), 'audit_log', ['operation'], unique=False)
    op.create_table('decrypt_failures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('envelope_id', sa.String(length=36), nullable=True),
    sa.Column('reason_code', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decrypt_failures_actor'), 'decrypt_failures', ['actor'], unique=False)
    op.create_index(op.f('ix_decrypt_failures_envelope_id'), 'decrypt_failures', ['envelope_id'], unique=False)
    op.create_table('erasure_certificates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=128), nullable=False),
    sa.Column('subject_key_id', sa.String(length=36), nullable=False),
    sa.Column('records_unreadable', sa.Integer(), nullable=False),
    sa.Column('tables_affected', sa.JSON(), nullable=False),
    sa.Column('operator', sa.String(length=128), nullable=False),
    sa.Column('approval_chain', sa.JSON(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('signature', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erasure_certificates_subject_id'), 'erasure_certificates', ['subject_id'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('keks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('algorithm', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('provider_ref', sa.String(length=128), nullable=False),
    sa.Column('provider_name', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deprecated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('destroyed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keks_state'), 'keks', ['state'], unique=False)
    op.create_index('ux_keks_single_active', 'keks', ['state'], unique=True, sqlite_where=sa.text("state = 'active'"), postgresql_where=sa.text("state = 'active'"))
    op.create_table('operators',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_hash'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rotation_interval_days', sa.Integer(), nullable=False),
    sa.Column('alert_threshold_days', sa.Integer(), nullable=False),
    sa.Column('active_provider', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rewrap_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('from_kek_id', sa.String(length=36), nullable=False),
    sa.Column('to_kek_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('done', sa.Integer(), nullable=False),
    sa.Column('cursor', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_kek_id'], ['keks.id'], ),
    sa.ForeignKeyConstraint(['to_kek_id'], ['keks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rewrap_jobs_state'), 'rewrap_jobs', ['state'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('operator_id', sa.String(length=36), nullable=False),
    sa.Column('provider_name', sa.String(length=16), nullable=False),
    sa.Column('provider_connected', sa.Boolean(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=128), nullable=False),
    sa.Column('kek_id', sa.String(length=36), nullable=False),
    sa.Column('algorithm', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('wrapped_key', sa.LargeBinary(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('last_access_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('destroyed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('destroyed_by', sa.String(length=128), nullable=True),
    sa.Column('destroyed_approval_id', sa.String(length=36), nullable=True),
    sa.Column('destroyed_record_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kek_id'], ['keks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_keys_kek_id'), 'subject_keys', ['kek_id'], unique=False)
    op.create_index(op.f('ix_subject_keys_state'), 'subject_keys', ['state'], unique=False)
    op.create_index(op.f('ix_subject_keys_subject_id'), 'subject_keys', ['subject_id'], unique=True)
    op.create_table('envelopes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('v', sa.Integer(), nullable=False),
    sa.Column('alg', sa.String(length=32), nullable=False),
    sa.Column('kek_id', sa.String(length=36), nullable=False),
    sa.Column('subject_key_id', sa.String(length=36), nullable=False),
    sa.Column('wrapped_dek', sa.LargeBinary(), nullable=False),
    sa.Column('dek_nonce', sa.LargeBinary(), nullable=False),
    sa.Column('data_nonce', sa.LargeBinary(), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('tag', sa.LargeBinary(), nullable=False),
    sa.Column('table_name', sa.String(length=128), nullable=False),
    sa.Column('column_name', sa.String(length=128), nullable=False),
    sa.Column('record_id', sa.String(length=128), nullable=False),
    sa.Column('subject_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kek_id'], ['keks.id'], ),
    sa.ForeignKeyConstraint(['subject_key_id'], ['subject_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_envelopes_record_id'), 'envelopes', ['record_id'], unique=False)
    op.create_index(op.f('ix_envelopes_subject_id'), 'envelopes', ['subject_id'], unique=False)
    op.create_index(op.f('ix_envelopes_subject_key_id'), 'envelopes', ['subject_key_id'], unique=False)
    op.create_index(op.f('ix_envelopes_table_name'), 'envelopes', ['table_name'], unique=False)
    op.create_table('rewrap_failures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('subject_key_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['rewrap_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rewrap_failures_job_id'), 'rewrap_failures', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rewrap_failures_job_id'), table_name='rewrap_failures')
    op.drop_table('rewrap_failures')
    op.drop_index(op.f('ix_envelopes_table_name'), table_name='envelopes')
    op.drop_index(op.f('ix_envelopes_subject_key_id'), table_name='envelopes')
    op.drop_index(op.f('ix_envelopes_subject_id'), table_name='envelopes')
    op.drop_index(op.f('ix_envelopes_record_id'), table_name='envelopes')
    op.drop_table('envelopes')
    op.drop_index(op.f('ix_subject_keys_subject_id'), table_name='subject_keys')
    op.drop_index(op.f('ix_subject_keys_state'), table_name='subject_keys')
    op.drop_index(op.f('ix_subject_keys_kek_id'), table_name='subject_keys')
    op.drop_table('subject_keys')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_rewrap_jobs_state'), table_name='rewrap_jobs')
    op.drop_table('rewrap_jobs')
    op.drop_table('system_settings')
    op.drop_table('operators')
    op.drop_index('ux_keks_single_active', table_name='keks', sqlite_where=sa.text("state = 'active'"), postgresql_where=sa.text("state = 'active'"))
    op.drop_index(op.f('ix_keks_state'), table_name='keks')
    op.drop_table('keks')
    op.drop_table('idempotency_records')
    op.drop_index(op.f('ix_erasure_certificates_subject_id'), table_name='erasure_certificates')
    op.drop_table('erasure_certificates')
    op.drop_index(op.f('ix_decrypt_failures_envelope_id'), table_name='decrypt_failures')
    op.drop_index(op.f('ix_decrypt_failures_actor'), table_name='decrypt_failures')
    op.drop_table('decrypt_failures')
    op.drop_index(op.f('ix_audit_log_operation'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_key_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_digest'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_approvals_target_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_status'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_operation'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_table('alerts')
    # ### end Alembic commands ###
